---
- hosts: bap_client_service
  roles:
    - { role: docker, tags: docker }
    - { role: awscli, tags: awscli }
    - { role: beckn_service, tags: beckn_one_sandbox_bap_client }
  become: yes
  vars:
    service_name: beckn_one_sandbox_bap_client
    service_description: BAP Client Service
    service_port: 9001
    expose_ports: -p {{ service_port }}:{{ service_port }}
    mount_points: -v {{ service_dir }}/application.yml:/usr/local/lib/application.yml
  tags: deploy_beckn_one_sandbox_bap
