name: Staging deployment of backend
on:
  push:
    branches:
    - main
    paths:
    - backend/**
  workflow_run:
    workflows: ["DTOS Build"]
    types:
      - completed    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: deploying changes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.BACKENDHOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd taxi-reference-BAP/backend
          git checkout main
          git pull
          SHORT_SHA=$(git rev-parse --short HEAD)
          docker build -t client:$SHORT_SHA -f client.dockerfile .
          docker stop client
          docker rm client
          docker run -d --network "host"  --name client client:$SHORT_SHA
          echo "printing docker image sha"
          docker images --no-trunc --quiet client:$SHORT_SHA
