name: Staging deployment of taxibap-frontend
on:
  push:
    branches:
    - main
    paths:
    - FrontEnd/**
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: deploying changes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.STAGINGHOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd taxi-reference-BAP/FrontEnd
          git checkout main
          git pull
          yarn
          yarn build
          pm2 kill
          sleep 10
          pm2 start "yarn start" --name taxibap-staging
