name: Staging deployment
on:
  push:
    branches:
    - main
    paths:
    - Frontend
jobs:
  build:
    runs-on: [ self-hosted, linux ]

    steps:
      - name: Build and deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGINGHOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd taxi-reference-BAP/FrontEnd
            git checkout main
            git pull
            yarn
            yarn build
            pm2 kill
            sleep 10
            pm2 start "yarn start" --name taxibap-staging
