name: Staging deployment of Mobility Protocol Server
on:
  push:
    branches:
    - main
    paths:
    - protocol-server/**
jobs:
  build:
    name: Build
    runs-on: [ self-hosted, linux ]
    steps:
    - name: deploying changes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROTOCOLHOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd taxi-reference-BAP/protocol-server
          git checkout main
          git pull
          npm install
          npm run build
          pm2 kill
          sleep 10
          pm2 start
